services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  authentication:
    build: ./authentication/auth
    image: alexa151/faks-projekat-pisibp:Auth-${IMAGE_TAG}
    environment:
      REDIS_URL: redis://redis:6379
      JWT_SECRET: secret
      JWT_REFRESH_SECRET: refreshsecret
    depends_on:
      - redis
    ports:
      - "3004:3004"

  logout:
    build: ./authentication/logout
    image: alexa151/faks-projekat-pisibp:Logout-${IMAGE_TAG}
    environment:
      REDIS_URL: redis://redis:6379
      JWT_SECRET: secret
    depends_on:
      - redis
    ports:
      - "3003:3003"
